#!/bin/bash

make clean
git checkout $1
git checkout master plot_one date pages todo_sum words_sum Makefile
timeout 120s make

if [ $? -eq 124 ]; then
  echo "ERR"
else
  d=`./date`
  p=`./pages`
  t=`./todo_sum`
  w=`./words_sum`
  echo "d, p, t, w: "$d", "$p", "$t", "$w
fi
